"""empty message

Revision ID: 19830452806f
Revises: d959529c1aeb
Create Date: 2023-07-28 09:56:20.024880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19830452806f'
down_revision = 'd959529c1aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=250), nullable=True),
    sa.Column('fav_planet', sa.String(length=250), nullable=True),
    sa.Column('fav_people', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
