"""empty message

Revision ID: d53a5d93c850
Revises: 19830452806f
Create Date: 2023-07-31 08:46:05.934814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53a5d93c850'
down_revision = '19830452806f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_fav', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('people_fav', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'people', ['people_fav'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planet_fav'], ['id'])
        batch_op.drop_column('fav_planet')
        batch_op.drop_column('fav_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_people', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fav_planet', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('people_fav')
        batch_op.drop_column('planet_fav')

    # ### end Alembic commands ###
